### ISSUE TITLE
.NET Foundation CLA

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/.github#4]
We have an org-wide CLA here (since #2) with @dotnet-policy-service watching for compliance. I'm OK with various CLAs, but what bugs me here is that

> This Contribution License Agreement ( “Agreement” ) is agreed to by the party signing below ( “You” ),
and conveys certain license rights to the .NET Foundation ( “.NET Foundation” ) for Your contributions to
.NET Foundation open source projects.

I don't quite understand the relationship between Neo and .NET Foundation and why we should be giving some rights to .NET Foundation (and not Neo Foundation, for example). Is this policy valid, do we need it?

**Comment by shargon** [comment]
We can remove it
